- name: Ensure sonar directory exists
  file:
    path: "{{ sonar_system_dir }}"
    state: directory
    mode: 0755

- name: Download sonar file
  get_url:
    url: "https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-{{ sonar_version }}.zip"
    dest: "{{ sonar_system_dir }}"
    checksum: "{{ sonar_check_sum_algorithm }}:{{ sonar_check_sum_hash }}"

- name: Unarchive sonar file
  unarchive:
    src: "{{ sonar_system_dir }}/sonarqube-{{ sonar_version }}.zip"
    dest: "{{ sonar_system_dir }}"
    owner: "{{ sonar_service_user }}"
    remote_src: yes
